trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '6.0.x'
  displayName: 'Use .NET SDK'
  
- script: dotnet build --configuration Release
  displayName: 'Build'
- script: pwsh bin/Debug/net6.0/playwright.ps1 install --with-deps
  displayName: 'Install Playwright browsers'
- script: dotnet test --configuration Release
  displayName: 'Run tests'