trigger:
  branches:
    include:
    - develop
    - master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '$(Build.SourcesDirectory)\PlaywrightDemo\PlaywrightDemo.sln'
  projects: '$(Build.SourcesDirectory)\PlaywrightDemo\PlaywrightDemo.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet tool installer'
  
- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'NuGet restore packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: sdk
    version: '7.0.x'

- script: dotnet build --configuration $(buildConfiguration) $(solution)
  displayName: 'Build'

- script: |
    dir $(Build.SourcesDirectory)\PlaywrightDemo\bin\
  displayName: 'List files in directory'

- script: pwsh $(Build.SourcesDirectory)\PlaywrightDemo\bin\Release\net7.0\playwright.ps1 install
  displayName: 'Install Playwright browsers'

- script: dotnet test $(solution)
  displayName: 'Run tests'

